import '../models/product_model.dart';

List<Product> mobile = [
  Product(
    id: 1,
    name: "OnePlus 9 Pro",
    description: '6 GB RAM, 128GB Storage',
    dummyPrice: '₹ 35,999',
    discountPrice: '₹ 38,899',
    price: 35999,
    imgUrl: 'assets/images/oneplus2.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 2,
    name: 'Samsung Galaxy S22 Uitra',
    description: "12GB RAM, 256GB Storage",
    dummyPrice: '₹ 1,09,999',
    discountPrice: '₹ 1,31,999',
    price: 109999,
    imgUrl: 'assets/images/samsung.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 3,
    name: "OnePlus Nord N200 5G",
    description: "6GB RAM, 128GB Storage",
    dummyPrice: '₹ 28,499',
    discountPrice: '₹ 34,999',
    price: 28499,
    imgUrl: 'assets/images/oneplus.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 4,
    name: "Oppo Reno 5 Pro 5G",
    description: "8GB RAM, 256GB Storage",
    dummyPrice: '₹ 30,000',
    discountPrice: '₹ 33,499',
    price: 30000,
    imgUrl: 'assets/images/oppo.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 5,
    name: 'iPhone 14 pro max',
    description: 'iPhone 14 pro max (128GB) - Gold',
    dummyPrice: '₹ 1,39,999',
    discountPrice: '₹ 1,49,999',
    price: 139999,
    imgUrl: 'assets/images/iphone.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 6,
    name: "iQOO Z6 Lite 5G",
    description: "6GB RAM, 256GB Storage",
    dummyPrice: '₹ 13,499',
    discountPrice: '₹ 15,499',
    price: 13499,
    imgUrl: 'assets/images/iqoo.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 7,
    name: 'Redmi 11 prime 5G',
    description: "Thunder black, 4GB RAM, 64GB Storage",
    dummyPrice: '₹ 28,499',
    discountPrice: '₹ 34,999',
    price: 28499,
    imgUrl: 'assets/images/redmi.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 8,
    name: 'Vivo V20',
    description: 'Chromatic Blue, 6GB RAM, 128GB Storage',
    dummyPrice: '₹ 23,499',
    discountPrice: '₹ 24,999',
    price: 23499,
    imgUrl: 'assets/images/v20.png',
    itemQuantity: 1,
    isLiked: false,
  ),
];

List<Product> fashion = [
  Product(
    id: 1,
    name: 'Classic T-Shirt',
    description: 'Ben martin men classic t-shirt',
    dummyPrice: '₹ 799',
    discountPrice: '₹ 999',
    price: 799,
    imgUrl: 'assets/images/1.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 2,
    name: 'Cotton hoodie',
    description: "Men's Cotton Clothing Neck Hoodies",
    dummyPrice: '₹ 1,299',
    discountPrice: '₹ 1,699',
    price: 1299,
    imgUrl: 'assets/images/2.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 3,
    name: "Men's Kurta suit",
    description: "Bright yellow Men's kurta suit",
    dummyPrice: '₹ 499',
    discountPrice: '₹ 899',
    price: 499,
    imgUrl: 'assets/images/3.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 4,
    name: "Men's Classic Shirt",
    description: "Men's classic shirt with cotton clothing",
    dummyPrice: '₹ 1,000',
    discountPrice: '₹ 1,299',
    price: 1000,
    imgUrl: 'assets/images/4.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 5,
    name: 'T-Shirt',
    description: "Men's classic t-shirt",
    dummyPrice: '₹ 699',
    discountPrice: '₹ 890',
    price: 699,
    imgUrl: 'assets/images/5.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 6,
    name: "Classic Shirt",
    description: "Men's Cotton Clothing shirt",
    dummyPrice: '₹ 1,499',
    discountPrice: '₹ 1,999',
    price: 1499,
    imgUrl: 'assets/images/6.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 7,
    name: 'T-shirt',
    description: "Men's classic t-shirt",
    dummyPrice: '₹ 499',
    discountPrice: '₹ 799',
    price: 499,
    imgUrl: 'assets/images/7.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 8,
    name: "Men's Hoodie",
    description: 'New cotton heavy blend hoodie',
    dummyPrice: '₹ 799',
    discountPrice: '₹ 1,299',
    price: 799,
    imgUrl: 'assets/images/8.png',
    itemQuantity: 1,
    isLiked: false,
  ),
];

List<Product> furniture = [
  Product(
    id: 1,
    name: 'Sofa',
    description: 'Vintage French Country Sofa',
    dummyPrice: '₹ 23,499',
    discountPrice: '₹ 24,499',
    price: 23499,
    imgUrl: 'assets/images/sofa.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 2,
    name: 'Study table',
    description: 'French corner study table in blue finish',
    dummyPrice: '₹ 1,09,999',
    discountPrice: '₹ 1,31,999',
    price: 109999,
    imgUrl: 'assets/images/table.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 3,
    name: 'Chair',
    description: 'Modern Molded Arm chair with wood leg',
    dummyPrice: '₹ 1,299',
    discountPrice: '₹ 1,599',
    price: 1299,
    imgUrl: 'assets/images/chair.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 4,
    name: 'Dinning table',
    description: 'Baumhaus Walnut 150cm Dining table',
    dummyPrice: '₹ 14,999',
    discountPrice: '₹ 26,499',
    price: 14999,
    imgUrl: 'assets/images/dinning.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 5,
    name: 'Bed',
    description: 'Modern designed bed',
    dummyPrice: '₹ 23,499',
    discountPrice: '₹ 24,999',
    price: 23499,
    imgUrl: 'assets/images/bed.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 6,
    name: 'TV wall unit',
    description: 'West point TV Wall unit',
    dummyPrice: '₹ 24,999',
    discountPrice: '₹ 26,999',
    price: 24499,
    imgUrl: 'assets/images/tvpoint.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 7,
    name: 'Chair',
    description: 'Solid wood Rocking chair in honey oak finish',
    dummyPrice: '₹ 2,000',
    discountPrice: '₹ 2,180',
    price: 2000,
    imgUrl: 'assets/images/chair2.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 8,
    name: 'Chair',
    description: 'A French Style Painted open arm chair',
    dummyPrice: '₹ 3,299',
    discountPrice: '₹ 3,799',
    price: 3299,
    imgUrl: 'assets/images/chair3.png',
    itemQuantity: 1,
    isLiked: false,
  ),
];

List<Product> beauty = [
  Product(
    id: 1,
    name: 'CLINIQUE Skin Care',
    description: 'Oil control face wash for men',
    dummyPrice: '₹ 1,499',
    discountPrice: '₹ 1,999',
    price: 1499,
    imgUrl: 'assets/images/1st.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 2,
    name: 'Dove+ skin Care',
    description: 'Control skin dryness',
    dummyPrice: '₹ 999',
    discountPrice: '₹ 1,299',
    price: 999,
    imgUrl: 'assets/images/2nd.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 3,
    name: 'Brickell face moisturizer',
    description: 'Brickell face moisturizer with Aloe and Coconut',
    dummyPrice: '₹ 1,999',
    discountPrice: '₹ 2,399',
    price: 1999,
    imgUrl: 'assets/images/3rd.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 4,
    name: "Dior Men's Deodorant",
    description: "Dior Men's Sauvage Deodorant Spray",
    dummyPrice: '₹ 1,000',
    discountPrice: '₹ 1,399',
    price: 1000,
    imgUrl: 'assets/images/4th.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 5,
    name: 'Brickell Hair Conditioner',
    description: 'Brickell Hair Conditioner with Aloe and Vitamin E',
    dummyPrice: '₹ 499',
    discountPrice: '₹ 799',
    price: 499,
    imgUrl: 'assets/images/5th.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 6,
    name: 'Neutrogena Face Lotion',
    description: 'Neutrogena Face Lotion with sunscreen broad spectrum',
    dummyPrice: '₹ 999',
    discountPrice: '₹ 1,299',
    price: 999,
    imgUrl: 'assets/images/6th.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 7,
    name: 'Suave Hair Styling Gel',
    description: "Suave men's hair styling gel",
    dummyPrice: '₹ 599',
    discountPrice: '₹ 899',
    price: 599,
    imgUrl: 'assets/images/7th.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 8,
    name: 'Dove Men+Care Deodorant',
    description: "Dove's stick Moisturizing Deodorant",
    dummyPrice: '₹ 1,299',
    discountPrice: '₹ 1,599',
    price: 1299,
    imgUrl: 'assets/images/8th.png',
    itemQuantity: 1,
    isLiked: false,
  ),
];

List<Product> grocery = [
  Product(
    id: 1,
    name: 'Plain Almonds',
    description: '100% natural 200 gm Almonds',
    dummyPrice: '₹ 700',
    discountPrice: '₹ 800',
    price: 700,
    imgUrl: 'assets/images/almond.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 2,
    name: 'Real Mosambi juice',
    description: "Real Mosambi juice with fruit goodness",
    dummyPrice: '₹ 150',
    discountPrice: '₹ 180',
    price: 150,
    imgUrl: 'assets/images/juice.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 3,
    name: "Alpino Peanut butter",
    description: "Alpino peanut butter with 1 kg net weight",
    dummyPrice: '₹ 1,499',
    discountPrice: '₹ 1,899',
    price: 1499,
    imgUrl: 'assets/images/butter.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 4,
    name: "Basmati rice",
    description: "Daawat traditional basmati rice",
    dummyPrice: '₹ 600',
    discountPrice: '₹ 799',
    price: 600,
    imgUrl: 'assets/images/daawat.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 5,
    name: 'Biscuit',
    description: "Sunfeast dark fantasy choco fills",
    dummyPrice: '₹ 50',
    discountPrice: '₹ 600',
    price: 50,
    imgUrl: 'assets/images/dark.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 6,
    name: "Fortune Besan flour",
    description: "Made from 100% chana dal",
    dummyPrice: '₹ 50',
    discountPrice: '₹ 52',
    price: 50,
    imgUrl: 'assets/images/besan.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 7,
    name: 'Maggie',
    description: "Maggi 2-minute noodles with quality ingredients",
    dummyPrice: '₹ 25',
    discountPrice: '₹ 27',
    price: 25,
    imgUrl: 'assets/images/maggie.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 8,
    name: "Ketchup",
    description: 'kissan tomato ketchup glass',
    dummyPrice: '₹ 130',
    discountPrice: '₹ 145',
    price: 130,
    imgUrl: 'assets/images/sauce.png',
    itemQuantity: 1,
    isLiked: false,
  ),
];

List<Product> shoes = [
  Product(
    id: 1,
    name: "Men's leather shoes",
    description: "Men's leather lined monk strap slip shoes",
    dummyPrice: '₹ 1,399',
    discountPrice: '₹ 1,499',
    price: 1399,
    imgUrl: 'assets/images/shoes1.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 2,
    name: 'Sneakers skate shoe',
    description: "Nike's sneakers shoes",
    dummyPrice: '₹ 2,399',
    discountPrice: '₹ 2,799',
    price: 2399,
    imgUrl: 'assets/images/shoes2.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 3,
    name: "Men's athletic shoes",
    description: "Men's athletic shoes with white and black color",
    dummyPrice: '₹ 1,499',
    discountPrice: '₹ 999',
    price: 1499,
    imgUrl: 'assets/images/shoes3.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 4,
    name: "Nike men's shoes",
    description: "Nike men's Running shoes!",
    dummyPrice: '₹ 4,000',
    discountPrice: '₹ 4,499',
    price: 4000,
    imgUrl: 'assets/images/shoes4.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 5,
    name: 'SparX Navy Sports shoes',
    description: "SparX's Sports shoes",
    dummyPrice: '₹ 3,499',
    discountPrice: '₹ 3,999',
    price: 3999,
    imgUrl: 'assets/images/shoes5.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 6,
    name: "Black shoes",
    description: "PUMA black sports shoes",
    dummyPrice: '₹ 6,499',
    discountPrice: '₹ 6,999',
    price: 6499,
    imgUrl: 'assets/images/shoes6.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 7,
    name: "Puma Men's shoes",
    description: "Puma men purple Running shoes",
    dummyPrice: '₹ 8,299',
    discountPrice: '₹ 9,899',
    price: 8299,
    imgUrl: 'assets/images/shoes7.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 8,
    name: "Men's leather Shoes",
    description: "British Fashion Men's leather shoes",
    dummyPrice: '₹ 5,999',
    discountPrice: '₹ 6,499',
    price: 5999,
    imgUrl: 'assets/images/shoes8.png',
    itemQuantity: 1,
    isLiked: false,
  ),
];

List<Product> home = [
  Product(
    id: 1,
    name: "Frameless Television",
    description: "Design frameless Television TV Plasma",
    dummyPrice: '₹ 39,999',
    discountPrice: '₹ 45,999',
    price: 39999,
    imgUrl: 'assets/images/tv.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 2,
    name: 'Water purifier',
    description: "White, Blue Pearl Emerald Water Purifier",
    dummyPrice: '₹ 25,299',
    discountPrice: '₹ 28,499',
    price: 25299,
    imgUrl: 'assets/images/filter.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 3,
    name: "Microwave oven",
    description: "Samsung latest microwave oven",
    dummyPrice: '₹ 9,999',
    discountPrice: '₹ 12,499',
    price: 9999,
    imgUrl: 'assets/images/oven.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 4,
    name: "AC",
    description: "Samsung Reimagines AC design with Triangle body",
    dummyPrice: '₹ 25,000',
    discountPrice: '₹ 29,499',
    price: 25000,
    imgUrl: 'assets/images/ac.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 5,
    name: 'Treadmill',
    description: 'Goplus folding treadmill',
    dummyPrice: '₹ 32,499',
    discountPrice: '₹ 35,890',
    price: 32499,
    imgUrl: 'assets/images/treadmill.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 6,
    name: "Cycle",
    description: "Cycle for indoor exercise",
    dummyPrice: '₹ 9,499',
    discountPrice: '₹ 12,999',
    price: 9499,
    imgUrl: 'assets/images/cycle.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 7,
    name: "Fridge",
    description: "Samsung's latest fridge comes with a LCD touchscreen",
    dummyPrice: '₹ 1,28,499',
    discountPrice: '₹ 1,40,999',
    price: 128499,
    imgUrl: 'assets/images/fridge.png',
    itemQuantity: 1,
    isLiked: false,
  ),
  Product(
    id: 8,
    name: "Wall Clock",
    description: "Estron analog latest stylish wall clock",
    dummyPrice: '₹ 5,999',
    discountPrice: '₹ 6,499',
    price: 5999,
    imgUrl: 'assets/images/wall.png',
    itemQuantity: 1,
    isLiked: false,
  ),
];